// defines.prototypes from Factorio 1.1.31, the first version that has this.
export const definesPrototypesFallback = {
	"achievement": {
		"achievement": 0,
		"build-entity-achievement": 0,
		"combat-robot-count": 0,
		"construct-with-robots-achievement": 0,
		"deconstruct-with-robots-achievement": 0,
		"deliver-by-robots-achievement": 0,
		"dont-build-entity-achievement": 0,
		"dont-craft-manually-achievement": 0,
		"dont-use-entity-in-energy-production-achievement": 0,
		"finish-the-game-achievement": 0,
		"group-attack-achievement": 0,
		"kill-achievement": 0,
		"player-damaged-achievement": 0,
		"produce-achievement": 0,
		"produce-per-hour-achievement": 0,
		"research-achievement": 0,
		"train-path-achievement": 0,
	},
	"ambient-sound": {
		"ambient-sound": 0,
	},
	"ammo-category": {
		"ammo-category": 0,
	},
	"animation": {
		"animation": 0,
	},
	"autoplace-control": {
		"autoplace-control": 0,
	},
	"custom-input": {
		"custom-input": 0,
	},
	"damage-type": {
		"damage-type": 0,
	},
	"decorative": {
		"optimized-decorative": 0,
	},
	"editor-controller": {
		"editor-controller": 0,
	},
	"entity": {
		"accumulator": 0,
		"ammo-turret": 0,
		"arithmetic-combinator": 0,
		"arrow": 0,
		"artillery-flare": 0,
		"artillery-projectile": 0,
		"artillery-turret": 0,
		"artillery-wagon": 0,
		"assembling-machine": 0,
		"beacon": 0,
		"beam": 0,
		"boiler": 0,
		"burner-generator": 0,
		"car": 0,
		"cargo-wagon": 0,
		"character": 0,
		"character-corpse": 0,
		"cliff": 0,
		"combat-robot": 0,
		"constant-combinator": 0,
		"construction-robot": 0,
		"container": 0,
		"corpse": 0,
		"curved-rail": 0,
		"decider-combinator": 0,
		"deconstructible-tile-proxy": 0,
		"electric-energy-interface": 0,
		"electric-pole": 0,
		"electric-turret": 0,
		"entity-ghost": 0,
		"explosion": 0,
		"fire": 0,
		"fish": 0,
		"flame-thrower-explosion": 0,
		"fluid-turret": 0,
		"fluid-wagon": 0,
		"flying-text": 0,
		"furnace": 0,
		"gate": 0,
		"generator": 0,
		"heat-interface": 0,
		"heat-pipe": 0,
		"highlight-box": 0,
		"infinity-container": 0,
		"infinity-pipe": 0,
		"inserter": 0,
		"item-entity": 0,
		"item-request-proxy": 0,
		"lab": 0,
		"lamp": 0,
		"land-mine": 0,
		"leaf-particle": 0,
		"linked-belt": 0,
		"linked-container": 0,
		"loader": 0,
		"loader-1x1": 0,
		"locomotive": 0,
		"logistic-container": 0,
		"logistic-robot": 0,
		"market": 0,
		"mining-drill": 0,
		"offshore-pump": 0,
		"particle": 0,
		"particle-source": 0,
		"pipe": 0,
		"pipe-to-ground": 0,
		"player-port": 0,
		"power-switch": 0,
		"programmable-speaker": 0,
		"projectile": 0,
		"pump": 0,
		"radar": 0,
		"rail-chain-signal": 0,
		"rail-remnants": 0,
		"rail-signal": 0,
		"reactor": 0,
		"resource": 0,
		"roboport": 0,
		"rocket-silo": 0,
		"rocket-silo-rocket": 0,
		"rocket-silo-rocket-shadow": 0,
		"simple-entity": 0,
		"simple-entity-with-force": 0,
		"simple-entity-with-owner": 0,
		"smoke": 0,
		"smoke-with-trigger": 0,
		"solar-panel": 0,
		"speech-bubble": 0,
		"spider-leg": 0,
		"spider-vehicle": 0,
		"splitter": 0,
		"sticker": 0,
		"storage-tank": 0,
		"straight-rail": 0,
		"stream": 0,
		"tile-ghost": 0,
		"train-stop": 0,
		"transport-belt": 0,
		"tree": 0,
		"turret": 0,
		"underground-belt": 0,
		"unit": 0,
		"unit-spawner": 0,
		"wall": 0,
	},
	"equipment": {
		"active-defense-equipment": 0,
		"battery-equipment": 0,
		"belt-immunity-equipment": 0,
		"energy-shield-equipment": 0,
		"generator-equipment": 0,
		"movement-bonus-equipment": 0,
		"night-vision-equipment": 0,
		"roboport-equipment": 0,
		"solar-panel-equipment": 0,
	},
	"equipment-category": {
		"equipment-category": 0,
	},
	"equipment-grid": {
		"equipment-grid": 0,
	},
	"fluid": {
		"fluid": 0,
	},
	"font": {
		"font": 0,
	},
	"fuel-category": {
		"fuel-category": 0,
	},
	"god-controller": {
		"god-controller": 0,
	},
	"gui-style": {
		"gui-style": 0,
	},
	"item": {
		"ammo": 0,
		"armor": 0,
		"blueprint": 0,
		"blueprint-book": 0,
		"capsule": 0,
		"copy-paste-tool": 0,
		"deconstruction-item": 0,
		"gun": 0,
		"item": 0,
		"item-with-entity-data": 0,
		"item-with-inventory": 0,
		"item-with-label": 0,
		"item-with-tags": 0,
		"mining-tool": 0,
		"module": 0,
		"rail-planner": 0,
		"repair-tool": 0,
		"selection-tool": 0,
		"spidertron-remote": 0,
		"tool": 0,
		"upgrade-item": 0,
	},
	"item-group": {
		"item-group": 0,
	},
	"item-subgroup": {
		"item-subgroup": 0,
	},
	"map-gen-presets": {
		"map-gen-presets": 0,
	},
	"map-settings": {
		"map-settings": 0,
	},
	"module-category": {
		"module-category": 0,
	},
	"mouse-cursor": {
		"mouse-cursor": 0,
	},
	"noise-expression": {
		"noise-expression": 0,
	},
	"noise-layer": {
		"noise-layer": 0,
	},
	"particle": {
		"optimized-particle": 0,
	},
	"recipe": {
		"recipe": 0,
	},
	"recipe-category": {
		"recipe-category": 0,
	},
	"resource-category": {
		"resource-category": 0,
	},
	"shortcut": {
		"shortcut": 0,
	},
	"sound": {
		"sound": 0,
	},
	"spectator-controller": {
		"spectator-controller": 0,
	},
	"sprite": {
		"sprite": 0,
	},
	"technology": {
		"technology": 0,
	},
	"tile": {
		"tile": 0,
	},
	"tile-effect": {
		"tile-effect": 0,
	},
	"tips-and-tricks-item": {
		"tips-and-tricks-item": 0,
	},
	"tips-and-tricks-item-category": {
		"tips-and-tricks-item-category": 0,
	},
	"trigger-target-type": {
		"trigger-target-type": 0,
	},
	"trivial-smoke": {
		"trivial-smoke": 0,
	},
	"tutorial": {
		"tutorial": 0,
	},
	"utility-constants": {
		"utility-constants": 0,
	},
	"utility-sounds": {
		"utility-sounds": 0,
	},
	"utility-sprites": {
		"utility-sprites": 0,
	},
	"virtual-signal": {
		"virtual-signal": 0,
	},
	"wind-sound": {
		"wind-sound": 0,
	},
};
